### ISSUE TITLE
Overflow in the Height card

### ISSUE THREAD

**Issue by aitrenI** [londonappbrewery/BMI-Calculator-Flutter-Completed#7]
After many trials I ran the given code for the complete app and have the same problem.

There is overflow in the middle card which contains the slider and height.

**Comment by nirajbais1** [comment]
Getting below Exception and unable to observe any code changes :

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while looking for parent data.:
Incorrect use of ParentDataWidget.

The following ParentDataWidgets are providing parent data to the same RenderObject:
- Expanded(flex: 1) (typically placed directly inside a Flex widget)
- Expanded(flex: 1) (typically placed directly inside a Flex widget)
However, a RenderObject can only receive parent data from at most one ParentDataWidget.

Usually, this indicates that at least one of the offending ParentDataWidgets listed above is not placed directly inside a compatible ancestor widget.

The ownership chain for the RenderObject that received the parent data was:
  Row ← Expanded ← Expanded ← Column ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._findAncestorParentDataElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:5341:11)
#1      RenderObjectElement._findAncestorParentDataElement (package:flutter/src/widgets/framework.dart:5355:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5680:61)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5376:5)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5943:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 502 libraries in 601ms.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Each child must be laid out exactly once.

**Comment by mohitnakum** [comment]
@aitrenI you can overcome it by using SingleChildScrollView

**Comment by mohitnakum** [comment]
Expanded(
            child: ReusableCard(
              colour: kActiveCardColour,
              cardChild: **SingleChildScrollView**(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Text(
                      'HEIGHT',
                      style: kLabelTextStyle,
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.baseline,
                      textBaseline: TextBaseline.alphabetic,
                      children: <Widget>[
                        Text(
                          height.toString(),
                          style: kNumberTextStyle,
                        ),
                        Text(
                          'cm',
                          style: kLabelTextStyle,
                        )
                      ],
                    ),
                    SliderTheme(
                      data: SliderTheme.of(context).copyWith(
                        inactiveTrackColor: Color(0xFF8D8E98),
                        activeTrackColor: Colors.white,
                        thumbColor: Color(0xFFEB1555),
                        overlayColor: Color(0x29EB1555),
                        thumbShape:
                            RoundSliderThumbShape(enabledThumbRadius: 15.0),
                        overlayShape:
                            RoundSliderOverlayShape(overlayRadius: 30.0),
                      ),
                      child: Slider(
                        value: height.toDouble(),
                        min: 120.0,
                        max: 220.0,
                        onChanged: (double newValue) {
                          setState(() {
                            height = newValue.round();
                          });
                        },
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
